name: Deploy Azure SignalR
on:
  push:
    branches:
      - main
    paths:
      - 'AppService/**'
      - 'DevOps/**'
      - '.github/workflows/deployment.yml'
  workflow_dispatch:

env:
  TERRAFORM_FILENAME: 'infra-signalr.tfstate'
  TERRAFORM_WORKING_DIRECTORY: './DevOps/Terraform/Infrastructures'
  TERRAFORM_STORAGE_ACCOUNT: 'tfstateexampleazfunc'
  TERRAFORM_CONTAINER_NAME: 'tfstatecontainer'
  TERRAFORM_RESOURCE_GROUP_NAME: 'rg-signal-example'

  APP_SERVICE_NAME: 'appservice-test-example'
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  PROJECT_TARGET_PATH: './AppService/AppService.csproj'
  SOLUTION_PATH: 'AppService.sln'
  BUILD_NAME: 'AppService'

jobs:

  # setup-infrastructure-on-test:
  #   runs-on: windows-latest
  #   environment: test
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v4

  #     - uses: nhatthaiquang-agilityio/Terraform-CI-CD/.github/actions/terraform@main
  #       id: run-terraform
  #       with:
  #         working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
  #         environment: 'test'
  #         arm-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
  #         arm-client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         arm-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #         arm-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         terraform-resource-group-name: ${{ env.TERRAFORM_RESOURCE_GROUP_NAME }}
  #         terraform-storage-account: ${{ env.TERRAFORM_STORAGE_ACCOUNT }}
  #         terraform-container-name: ${{ env.TERRAFORM_CONTAINER_NAME }}
  #         terraform-filename: 'test.${{ env.TERRAFORM_FILENAME }}'

  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: nhatthaiquang-agilityio/Terraform-CI-CD/.github/actions/build-package-dotnet@main
        id: build-package
        with:
          solution-path: ${{ env.SOLUTION_PATH }}
          build-target-path: ${{ env.PROJECT_TARGET_PATH }}
          build-name: ${{ env.BUILD_NAME }}

  deploy:
    needs: build
    runs-on: windows-latest
    environment: test
    steps:
      - name: 'Deploy Azure App Service'
        uses: nhatthaiquang-agilityio/Terraform-CI-CD/.github/actions/deploy-app-service@main
        id: azure-app-service
        with:
          azure-app-service-name: ${{ env.APP_SERVICE_NAME }}
          azure-app-service-package-path: ' ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          arm-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure-app-service-publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          artifact-name: 'app-service'