name: Deploy Azure SignalR
on:
  push:
    branches:
      - main
    paths:
      - 'AppService/**'
      - 'DevOps/**'
      - '.github/workflows/deployment.yml'
  workflow_dispatch:

env:
  TERRAFORM_FILENAME: 'infra-signalr.tfstate'
  TERRAFORM_WORKING_DIRECTORY: './DevOps/Terraform/Infrastructures'
  TERRAFORM_STORAGE_ACCOUNT: 'tfstateexampleazfunc'
  TERRAFORM_CONTAINER_NAME: 'tfstatecontainer'
  TERRAFORM_RESOURCE_GROUP_NAME: 'rg-signal-example'

  APP_SERVICE_NAME: 'appservice-test-example'
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:

  # setup-infrastructure-on-test:
  #   runs-on: windows-latest
  #   environment: test
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v4

  #     - uses: nhatthaiquang-agilityio/Terraform-CI-CD/.github/actions/terraform@main
  #       id: run-terraform
  #       with:
  #         working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
  #         environment: 'test'
  #         arm-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
  #         arm-client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         arm-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #         arm-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         terraform-resource-group-name: ${{ env.TERRAFORM_RESOURCE_GROUP_NAME }}
  #         terraform-storage-account: ${{ env.TERRAFORM_STORAGE_ACCOUNT }}
  #         terraform-container-name: ${{ env.TERRAFORM_CONTAINER_NAME }}
  #         terraform-filename: 'test.${{ env.TERRAFORM_FILENAME }}'

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: dotnet build ./AppService/AppService.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./AppService/AppService.csproj -c Release -o ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    needs: build
    runs-on: windows-latest
    environment: test
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v5
        with:
          name: .net-app

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}